# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"
    NameToUriType  = 2
    RouteOverWrite = true
# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    link  = "mysql:root:123@tcp(192.168.230.129:3306)/gf-demo"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true
# swagger api页面查看账号密码
[swagger]
    user        = "123"
    pass        = "123"
    schemes     = ["http"]
    version     = "1.0"
    title       = "示例服务API"
    description = """
`GoFrame`基础开发框架示例服务API接口文档。
    """
# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:root:123@tcp(192.168.230.129:3306)/gf-demo"
        tables = "user"
    # 构建 gf build
    [gfcli.build]
        name     = "my-application"
        arch     = "amd64"
        system   = "linux"
        mod      = "none"
        cgo      = 0
        pack     = "config,i18n,public,template" # 打包至二进制的目录
        version  = ""
        output   = "./bin"
        extra    = ""
